version: "3"
services:

  nginx:
    ports:
      - "3000:80"

  node-express:
    build:
      context: .
      args: 
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=jeremy
      - MONGO_PASSWORD=password
    command: npm run dev
