version: "3"
services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-express
      
  node-express:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jeremy 
      - MONGO_INITDB_ROOT_PASSWORD=password 
    volumes:
      - mongo-db:/data/db

volumes: 
  mongo-db: