version: "3"
services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"

  node-express:
    build:
      context: .
      args: 
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
      - MONGO_USER=jeremy
      - MONGO_PASSWORD=password
    command: node index.js
